config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :post_id, presence: true
  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments, dependent: :destroy
    # post should have a title and body to be added to db
    # validates_presence_of :title
    # validates_presence_of :body
    validates :title, presence: true
    validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    # Retrieve the id of the post that's passed in as a param
    @post = Post.find(params[:post_id])
    # @comment = Comment.new(comment_params)
    @comment = @post.comments.create(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js # create.js.erb   (allow controller to respond to JavaScript)
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
    <p>
        <!--  Then prints it out in strong emphasized. Uses a rails helper 
        method (time_ago_in_words) that takes when that comment was created
        and converts that to words.  -->
        <!-- <strong>Posted <%= time_ago_in_words(comment.created_at) %></strong><br /> -->
        Posted <%= time_ago_in_words(comment.created_at) %><br />
        <!-- Dumps out body of the comment -->
        <span id="addedComment"><%= h(comment.body) %></span>
    </p>
<% end %>

app/views/comments/_form.html.erb
# <%= form_for(@comment) do |f| %>
<!-- Modify the "New Comment" form to perform the POST request remotely -->
<%= form_for(@comment, remote: true) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.text_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
// ensure text returned by Ruby is valid JavaScript. hide the entire comment that's created
var new_comment = $("<%= escape_javascript(render(:partial => @comment))%>").hide();
// Find div w/id comments and prepend the new comment that was just created
$('#comments').prepend(new_comment);
// slowly fade in the new comment (comment.id)
$('#comment_<%= @comment.id %>').fadeIn('slow');
// reset the form to allow another comment to be submitted
$('#new_comment')[0].reset();

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, :class => "newCommentTextField" %>
  </div>
  <div class="actions">
    <%= f.submit "Create", :class => "submitBtn" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="breadcrumb"></div>

<div id="contentDiv">
<p id="notice"><%= notice %></p>

<div id="postListHeader">
  <div class="postListTitle">
    <h1>Listing Posts</h1>
  </div>
  <div class="createBtn">
    <%= link_to '+ New Post', new_post_path %>
  </div>
</div>

<table id="postsTable">
  <thead>
    <tr class="tableHeaderRow">
      <th>Title</th>
      <th id="tableHeaderBody">Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr class="tableBodyRow">
        <td class="titleCol"><%= post.title %></td>
        <td class="bodyCol"><%= post.body %></td>
        <td class="linksCol"><%= link_to 'Show', post %></td>
        <td class="linksCol"><%= link_to 'Edit', edit_post_path(post) %></td>
        <td class="linksCol"><span id="destroyBtn"><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></span></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>



</div>

<div class="breadcrumbBtm"></div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="breadcrumb"></div>

<div id="contentDiv">
<p id="notice"><%= notice %></p>

<div id="postTitle">
  <p class="postHeaderLabel">
    <!-- <span class="postHeaderLabel"> -->
      <!-- <strong>Title:</strong> -->
      Title:
    <!-- </span> -->
    <span class="postTitleText">
      <%= @post.title %>
    </span>
  </p>
</div>

<div id="postBody">
  <p class="postHeaderLabel">
  <!-- <p> -->
    <!-- <strong>Body:</strong> -->
    Body:
    <span class="postBodyText">
     <%= @post.body %>
    </span>
  </p>
</div>
<!-- Modifying view for a post to show its comments -->
<h2>Comments</h2>
<div id="comments">
    <!--  Render all the comments in reverse order so that most recent comments on top -->
    <%= render :partial => @post.comments.reverse %>
</div>

<div id="newCommentForm">
<!-- Add a form for adding new comments on the post page -->
<!-- make sure an Ajax request is being initiated using remote: true  -->
<%= form_for([@post, Comment.new], remote: true) do |f| %>
  <div id="addCommentTextField">
    <p>
      <!-- Label (text area header) and text area for entering a new comment -->
      <%= f.label :body, "New Comment", :class => "newCommentLabel" %><br />
      <%= f.text_area :body, :class => "newCommentTextField" %>
    </p>
  </div>
  <div id="addCommentBtn">
    <!-- Submit button w/ text "Add Comment" -->
    <p><%= f.submit "Add Comment", :class => "submitBtn" %></p>
  </div>
<% end %>
</div>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
</div>

<div class="breadcrumbBtm"></div>